import {
  Conversation,
  MaintenanceRequest,
  Message,
  PmUser,
  SiteVisitNote,
} from '../types/domain';

export const mockPmUser: PmUser = {
  id: 'pm-01',
  name: 'Alex Chen',
  email: 'alex.chen@rentalsmart.ca',
  role: 'PM',
  phone: '+1 604-555-0123',
  address: '1088 Georgia St W, Vancouver, BC',
  bio: 'Primary manager for Downtown and Burnaby portfolio.',
  emailNotifs: true,
  smsNotifs: true,
};

export const mockConversations: Conversation[] = [
  {
    id: 'conv-001',
    visitorAlias: 'Guest-8A2F',
    status: 'new',
    property: {
      id: 'prop-001',
      name: 'Harborview Residences',
      city: 'Vancouver',
      address: '1088 Georgia St W, Vancouver, BC',
      dataverseUrl:
        'https://org.crm.dynamics.com/main.aspx?etn=rs_property&pagetype=entityrecord&id=prop-001',
    },
    unit: {
      id: 'unit-1203',
      label: 'Unit 1203',
      bedrooms: 2,
      bathrooms: 2,
      rent: 3200,
      dataverseUrl:
        'https://org.crm.dynamics.com/main.aspx?etn=rs_unit&pagetype=entityrecord&id=unit-1203',
    },
    hasBot: true,
    botEscalated: true,
    unreadCount: 3,
    lastMessageAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'conv-002',
    visitorAlias: 'Guest-5K19',
    status: 'assigned',
    property: {
      id: 'prop-002',
      name: 'Maple Crest Towers',
      city: 'Burnaby',
      address: '4800 Kingsway, Burnaby, BC',
      dataverseUrl:
        'https://org.crm.dynamics.com/main.aspx?etn=rs_property&pagetype=entityrecord&id=prop-002',
    },
    unit: {
      id: 'unit-709',
      label: 'Unit 709',
      bedrooms: 1,
      bathrooms: 1,
      rent: 2550,
      dataverseUrl:
        'https://org.crm.dynamics.com/main.aspx?etn=rs_unit&pagetype=entityrecord&id=unit-709',
    },
    assignedPmId: 'pm-01',
    hasBot: true,
    botEscalated: false,
    unreadCount: 0,
    lastMessageAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
  },
  {
    id: 'conv-003',
    visitorAlias: 'Guest-ZY93',
    status: 'waiting',
    property: {
      id: 'prop-003',
      name: 'North Shore Flats',
      city: 'North Vancouver',
      address: '155 Lonsdale Ave, North Vancouver, BC',
      dataverseUrl:
        'https://org.crm.dynamics.com/main.aspx?etn=rs_property&pagetype=entityrecord&id=prop-003',
    },
    unit: {
      id: 'unit-404',
      label: 'Unit 404',
      bedrooms: 1,
      bathrooms: 1,
      rent: 2400,
      dataverseUrl:
        'https://org.crm.dynamics.com/main.aspx?etn=rs_unit&pagetype=entityrecord&id=unit-404',
    },
    assignedPmId: 'pm-01',
    hasBot: true,
    botEscalated: true,
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    conversationId: 'conv-001',
    senderType: 'visitor',
    senderName: 'Guest-8A2F',
    body: 'Hi, I have a leak under my kitchen sink. Can someone check today?',
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-002',
    conversationId: 'conv-001',
    senderType: 'bot',
    senderName: 'Rental Smart Bot',
    body: 'I can help with maintenance issues. Is water currently running?',
    createdAt: new Date(Date.now() - 38 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-003',
    conversationId: 'conv-001',
    senderType: 'visitor',
    senderName: 'Guest-8A2F',
    body: 'Yes, I turned off the valve but the cabinet is wet.',
    createdAt: new Date(Date.now() - 36 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-004',
    conversationId: 'conv-001',
    senderType: 'system',
    senderName: 'System',
    body: 'Bot escalated to property manager due to emergency keyword.',
    createdAt: new Date(Date.now() - 34 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-005',
    conversationId: 'conv-001',
    senderType: 'visitor',
    senderName: 'Guest-8A2F',
    body: 'Please let me know if someone can come before 6pm.',
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-006',
    conversationId: 'conv-002',
    senderType: 'pm',
    senderName: 'Alex Chen',
    body: 'Thanks, I have scheduled an inspection for tomorrow morning.',
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-007',
    conversationId: 'conv-002',
    senderType: 'visitor',
    senderName: 'Guest-5K19',
    body: 'Perfect, thank you!',
    createdAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-008',
    conversationId: 'conv-003',
    senderType: 'visitor',
    senderName: 'Guest-ZY93',
    body: 'Checking if parking spot assignment was updated?',
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
];

export const mockMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: 'mnt-001',
    conversationId: 'conv-001',
    propertyId: 'prop-001',
    unitId: 'unit-1203',
    title: 'Kitchen sink leak',
    summary: 'Water dripping from p-trap, cabinet floor wet.',
    status: 'new',
    priority: 'high',
    dataverseUrl:
      'https://org.crm.dynamics.com/main.aspx?etn=msdyn_workorder&pagetype=entityrecord&id=work-001',
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'mnt-002',
    conversationId: 'conv-002',
    propertyId: 'prop-002',
    unitId: 'unit-709',
    title: 'Bedroom heater noise',
    summary: 'Intermittent rattling sound from heater vent.',
    status: 'in_progress',
    priority: 'medium',
    dataverseUrl:
      'https://org.crm.dynamics.com/main.aspx?etn=msdyn_workorder&pagetype=entityrecord&id=work-002',
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mnt-003',
    propertyId: 'prop-003',
    unitId: 'unit-404',
    title: 'Lobby mailbox lock replacement',
    summary: 'Mailbox cluster lock replaced and tested.',
    status: 'done',
    priority: 'low',
    dataverseUrl:
      'https://org.crm.dynamics.com/main.aspx?etn=msdyn_workorder&pagetype=entityrecord&id=work-003',
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockVisitNotes: SiteVisitNote[] = [
  {
    id: 'visit-001',
    propertyId: 'prop-001',
    unitId: 'unit-1203',
    maintenanceRequestId: 'mnt-001',
    note: 'Visitor shared photo from under sink; standing water visible near p-trap.',
    source: 'chat',
    authorName: 'Guest-8A2F',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-002',
    propertyId: 'prop-001',
    unitId: 'unit-1203',
    maintenanceRequestId: 'mnt-001',
    note: 'Plumber dispatched. ETA 4:00 PM and tenant notified through chat.',
    source: 'maintenance',
    authorName: 'Alex Chen',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-003',
    propertyId: 'prop-001',
    unitId: 'unit-1203',
    maintenanceRequestId: 'mnt-001',
    note: 'Onsite check complete. Replaced p-trap gasket and dried cabinet base.',
    source: 'visit',
    authorName: 'Alex Chen',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-004',
    propertyId: 'prop-002',
    unitId: 'unit-709',
    maintenanceRequestId: 'mnt-002',
    note: 'Tenant sent short clip of heater rattle during night cycle.',
    source: 'chat',
    authorName: 'Guest-5K19',
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-005',
    propertyId: 'prop-002',
    unitId: 'unit-709',
    maintenanceRequestId: 'mnt-002',
    note: 'Inspected heater, likely loose vent plate. Vendor follow-up booked.',
    source: 'visit',
    authorName: 'Alex Chen',
    createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-006',
    propertyId: 'prop-002',
    unitId: 'unit-709',
    maintenanceRequestId: 'mnt-002',
    note: 'Vendor confirmed vent plate replacement and noise test passed.',
    source: 'maintenance',
    authorName: 'Alex Chen',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-007',
    propertyId: 'prop-003',
    unitId: 'unit-404',
    maintenanceRequestId: 'mnt-003',
    note: 'Visitor confirmed mailbox issue after key rotation and shared lock photo.',
    source: 'chat',
    authorName: 'Guest-ZY93',
    createdAt: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-008',
    propertyId: 'prop-003',
    unitId: 'unit-404',
    maintenanceRequestId: 'mnt-003',
    note: 'Hardware team assigned and parts ordered from supplier.',
    source: 'maintenance',
    authorName: 'Alex Chen',
    createdAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-009',
    propertyId: 'prop-003',
    unitId: 'unit-404',
    maintenanceRequestId: 'mnt-003',
    note: 'Lock replacement verified with tenant. Mailbox opens/closes normally.',
    source: 'maintenance',
    authorName: 'Alex Chen',
    createdAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  },
];
